import { Customer } from "../types/customer";

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: "CUS-1001",
    name: "Amaka Obi",
    profilePicture: null,
    phone: "+234 802 345 6789",
    email: "amaka.obi@gmail.com",
    address: { street: "12 Sapele Road", city: "Benin City", state: "Edo State" },
    joinedAt: new Date(Date.now() - 210 * 86400000).toISOString(),
    status: "Active",
    totalOrders: 34,
    totalSpent: 128400,
    lastOrderAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "CUS-1002",
    name: "Tunde Bakare",
    profilePicture: null,
    phone: "+234 803 456 7890",
    email: "tunde.bakare@yahoo.com",
    address: { street: "45 Airport Road", city: "Benin City", state: "Edo State" },
    joinedAt: new Date(Date.now() - 168 * 86400000).toISOString(),
    status: "Active",
    totalOrders: 21,
    totalSpent: 76500,
    lastOrderAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: "CUS-1003",
    name: "Grace Idahosa",
    profilePicture: null,
    phone: "+234 804 567 8901",
    email: "grace.idahosa@outlook.com",
    address: { street: "7 Ring Road, Off New Benin Market", city: "Benin City", state: "Edo State" },
    joinedAt: new Date(Date.now() - 95 * 86400000).toISOString(),
    status: "Active",
    totalOrders: 12,
    totalSpent: 41300,
    lastOrderAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: "CUS-1004",
    name: "Ifeoma Chukwu",
    profilePicture: null,
    phone: "+234 805 678 9012",
    email: "ifeoma.chukwu@gmail.com",
    address: { street: "3 Reservation Road", city: "Benin City", state: "Edo State" },
    joinedAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    status: "Inactive",
    totalOrders: 4,
    totalSpent: 15800,
    lastOrderAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: "CUS-1005",
    name: "Chidinma Eze",
    profilePicture: null,
    phone: "+234 806 789 0123",
    email: "chidinma.eze@gmail.com",
    address: { street: "9 Isekhure Street", city: "Benin City", state: "Edo State" },
    joinedAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    status: "Active",
    totalOrders: 7,
    totalSpent: 29900,
    lastOrderAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "CUS-1006",
    name: "Emeka Nwosu",
    profilePicture: null,
    phone: "+234 807 890 1234",
    email: "emeka.nwosu@gmail.com",
    address: { street: "22 Uselu Lagos Road", city: "Benin City", state: "Edo State" },
    joinedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    status: "Suspended",
    totalOrders: 1,
    totalSpent: 3200,
    lastOrderAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];