import { Driver } from "../types/driver";

const BASE_LAT = 6.335;
const BASE_LNG = 5.6037;

export const DEMO_DRIVERS: Driver[] = [
  {
    id: "1",
    driverId: "DRV-00021",
    firstName: "John",
    lastName: "Peter",
    email: "john.peter@kayora.com",
    phone: "+234 801 234 5678",
    profileImage: undefined,
    status: "active",
    vehicle: {
      brand: "Toyota",
      model: "Hilux",
      plateNumber: "AKD-324-AA",
      engineNumber: "ENG-33920184",
      chassisNumber: "CHS-77281940",
      image: undefined,
    },
    location: { latitude: BASE_LAT + 0.004, longitude: BASE_LNG + 0.003, speed: 38, updatedAt: new Date().toISOString() },
  },
  {
    id: "2",
    driverId: "DRV-00022",
    firstName: "Michael",
    lastName: "Osaro",
    email: "michael.osaro@kayora.com",
    phone: "+234 802 345 6789",
    profileImage: undefined,
    status: "delivering",
    vehicle: {
      brand: "Toyota",
      model: "Hiace",
      plateNumber: "AKD-245-KY",
      engineNumber: "ENG-88213409",
      chassisNumber: "CHS-99213409",
      image: undefined,
    },
    location: { latitude: BASE_LAT - 0.006, longitude: BASE_LNG + 0.008, speed: 44, updatedAt: new Date().toISOString() },
  },
  {
    id: "3",
    driverId: "DRV-00023",
    firstName: "Bassey",
    lastName: "Effiong",
    email: "bassey.effiong@kayora.com",
    phone: "+234 803 456 7890",
    profileImage: undefined,
    status: "break",
    vehicle: {
      brand: "Ford",
      model: "Transit",
      plateNumber: "EDS-118-FB",
      engineNumber: "ENG-11029384",
      chassisNumber: "CHS-22938471",
      image: undefined,
    },
    location: { latitude: BASE_LAT + 0.011, longitude: BASE_LNG - 0.005, speed: 0, updatedAt: new Date().toISOString() },
  },
  {
    id: "4",
    driverId: "DRV-00024",
    firstName: "Grace",
    lastName: "Idahosa",
    email: "grace.idahosa@kayora.com",
    phone: "+234 804 567 8901",
    profileImage: undefined,
    status: "offline",
    vehicle: {
      brand: "Toyota",
      model: "Hilux",
      plateNumber: "EDS-902-GI",
      engineNumber: "ENG-55019283",
      chassisNumber: "CHS-66019283",
      image: undefined,
    },
    location: { latitude: BASE_LAT - 0.002, longitude: BASE_LNG - 0.009, speed: 0, updatedAt: new Date(Date.now() - 3600000).toISOString() },
  },
  {
    id: "5",
    driverId: "DRV-00025",
    firstName: "Emeka",
    lastName: "Nwosu",
    email: "emeka.nwosu@kayora.com",
    phone: "+234 805 678 9012",
    profileImage: undefined,
    status: "active",
    vehicle: {
      brand: "Suzuki",
      model: "APV",
      plateNumber: "EDS-441-EN",
      engineNumber: "ENG-77102938",
      chassisNumber: "CHS-88102938",
      image: undefined,
    },
    location: { latitude: BASE_LAT + 0.007, longitude: BASE_LNG + 0.012, speed: 29, updatedAt: new Date().toISOString() },
  },
];