import { Order } from "../types/order";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600000).toISOString();

export const DEMO_ORDERS: Order[] = [
  {
    id: "KYA-88213",
    orderDate: hoursAgo(1),
    customer: {
      name: "Abigail Johnson",
      phone: "+234 802 345 6789",
      email: "abigail.johnson@gmail.com",
      profilePicture: null,
      deliveryAddress: "12 Sapele Road, Benin City, Edo State",
      nearestLandmark: "Opposite Guinness Nigeria",
      latitude: 6.339,
      longitude: 5.6216,
    },
    products: [{ bottleName: "Kayora Premium Water", size: "75cl", quantity: 4, price: 500, subtotal: 2000 }],
    amount: 2000,
    status: "Pending",
    paymentMethod: "Cash",
    paymentStatus: "Unpaid",
    transactionId: "TXN-000881",
    deliveryType: "Instant",
    scheduledDate: null,
    scheduledTime: null,
    priority: "Normal",
    delivery: { driverId: null, driverName: null, vehicle: null, estimatedDeliveryTime: null, distanceKm: null },
    timeline: [
      { label: "Order Created", timestamp: hoursAgo(1), completed: true },
      { label: "Payment Confirmed", timestamp: null, completed: false },
      { label: "Waiting For Assignment", timestamp: null, completed: false },
      { label: "Driver Assigned", timestamp: null, completed: false },
      { label: "Out For Delivery", timestamp: null, completed: false },
      { label: "Delivered", timestamp: null, completed: false },
    ],
    specialInstructions: "",
  },
  {
    id: "KYA-88198",
    orderDate: hoursAgo(3),
    customer: {
      name: "Tunde Bakare",
      phone: "+234 803 456 7890",
      email: "tunde.bakare@yahoo.com",
      profilePicture: null,
      deliveryAddress: "45 Airport Road, Benin City, Edo State",
      nearestLandmark: "Near Airport Road Roundabout",
      latitude: 6.3423,
      longitude: 5.6109,
    },
    products: [{ bottleName: "Kayora Premium Water", size: "1.5L", quantity: 6, price: 800, subtotal: 4800 }],
    amount: 4800,
    status: "Assigned",
    paymentMethod: "Transfer",
    paymentStatus: "Paid",
    transactionId: "TXN-000879",
    deliveryType: "Instant",
    scheduledDate: null,
    scheduledTime: null,
    priority: "High",
    delivery: {
      driverId: "2",
      driverName: "Michael Osaro",
      vehicle: "Toyota Hiace · AKD-245-KY",
      estimatedDeliveryTime: "35 min",
      distanceKm: 3.1,
    },
    timeline: [
      { label: "Order Created", timestamp: hoursAgo(3), completed: true },
      { label: "Payment Confirmed", timestamp: hoursAgo(3), completed: true },
      { label: "Waiting For Assignment", timestamp: hoursAgo(2), completed: true },
      { label: "Driver Assigned", timestamp: hoursAgo(1), completed: true },
      { label: "Out For Delivery", timestamp: null, completed: false },
      { label: "Delivered", timestamp: null, completed: false },
    ],
    specialInstructions: "Call on arrival, gate is usually locked.",
  },
  {
    id: "KYA-88176",
    orderDate: hoursAgo(6),
    customer: {
      name: "Grace Idahosa",
      phone: "+234 804 567 8901",
      email: "grace.idahosa@outlook.com",
      profilePicture: null,
      deliveryAddress: "7 Ring Road, Benin City, Edo State",
      nearestLandmark: "Behind New Benin Market",
      latitude: 6.3355,
      longitude: 5.6037,
    },
    products: [
      { bottleName: "Kayora Premium Water", size: "50cl", quantity: 10, price: 300, subtotal: 3000 },
      { bottleName: "Kayora Premium Water", size: "1L", quantity: 2, price: 650, subtotal: 1300 },
    ],
    amount: 4300,
    status: "Out For Delivery",
    paymentMethod: "Card",
    paymentStatus: "Paid",
    transactionId: "TXN-000862",
    deliveryType: "Instant",
    scheduledDate: null,
    scheduledTime: null,
    priority: "Normal",
    delivery: {
      driverId: "3",
      driverName: "Bassey Effiong",
      vehicle: "Ford Transit · EDS-118-FB",
      estimatedDeliveryTime: "12 min",
      distanceKm: 1.8,
    },
    timeline: [
      { label: "Order Created", timestamp: hoursAgo(6), completed: true },
      { label: "Payment Confirmed", timestamp: hoursAgo(6), completed: true },
      { label: "Waiting For Assignment", timestamp: hoursAgo(5), completed: true },
      { label: "Driver Assigned", timestamp: hoursAgo(4), completed: true },
      { label: "Out For Delivery", timestamp: hoursAgo(1), completed: true },
      { label: "Delivered", timestamp: null, completed: false },
    ],
    specialInstructions: "",
  },
  {
    id: "KYA-88150",
    orderDate: hoursAgo(20),
    customer: {
      name: "Ifeoma Chukwu",
      phone: "+234 805 678 9012",
      email: "ifeoma.chukwu@gmail.com",
      profilePicture: null,
      deliveryAddress: "3 Reservation Road, Benin City, Edo State",
      nearestLandmark: "Near GRA Gate 2",
      latitude: 6.3401,
      longitude: 5.6288,
    },
    products: [{ bottleName: "Kayora Premium Water", size: "5L", quantity: 3, price: 1500, subtotal: 4500 }],
    amount: 4500,
    status: "Delivered",
    paymentMethod: "Transfer",
    paymentStatus: "Paid",
    transactionId: "TXN-000844",
    deliveryType: "Instant",
    scheduledDate: null,
    scheduledTime: null,
    priority: "Normal",
    delivery: {
      driverId: "5",
      driverName: "Emeka Nwosu",
      vehicle: "Suzuki APV · EDS-441-EN",
      estimatedDeliveryTime: "Delivered",
      distanceKm: 2.4,
    },
    timeline: [
      { label: "Order Created", timestamp: hoursAgo(20), completed: true },
      { label: "Payment Confirmed", timestamp: hoursAgo(20), completed: true },
      { label: "Waiting For Assignment", timestamp: hoursAgo(19), completed: true },
      { label: "Driver Assigned", timestamp: hoursAgo(18), completed: true },
      { label: "Out For Delivery", timestamp: hoursAgo(17), completed: true },
      { label: "Delivered", timestamp: hoursAgo(16), completed: true },
    ],
    specialInstructions: "",
  },
  {
    id: "KYA-88142",
    orderDate: hoursAgo(28),
    customer: {
      name: "Michael Osaro",
      phone: "+234 806 789 0123",
      email: "michael.osaro2@gmail.com",
      profilePicture: null,
      deliveryAddress: "18 New Lagos Road, Benin City, Edo State",
      nearestLandmark: "Close to First Bank",
      latitude: 6.3288,
      longitude: 5.6142,
    },
    products: [{ bottleName: "Kayora Premium Water", size: "10L", quantity: 1, price: 2200, subtotal: 2200 }],
    amount: 2200,
    status: "Cancelled",
    paymentMethod: "Cash",
    paymentStatus: "Refunded",
    transactionId: "TXN-000831",
    deliveryType: "Instant",
    scheduledDate: null,
    scheduledTime: null,
    priority: "Normal",
    delivery: { driverId: null, driverName: null, vehicle: null, estimatedDeliveryTime: null, distanceKm: null },
    timeline: [
      { label: "Order Created", timestamp: hoursAgo(28), completed: true },
      { label: "Payment Confirmed", timestamp: hoursAgo(28), completed: true },
      { label: "Waiting For Assignment", timestamp: hoursAgo(27), completed: true },
      { label: "Driver Assigned", timestamp: null, completed: false },
      { label: "Out For Delivery", timestamp: null, completed: false },
      { label: "Delivered", timestamp: null, completed: false },
    ],
    specialInstructions: "Customer requested cancellation — duplicate order.",
  },
  {
    id: "KYA-88260",
    orderDate: hoursAgo(0.5),
    customer: {
      name: "Chidinma Eze",
      phone: "+234 807 890 1234",
      email: "chidinma.eze@gmail.com",
      profilePicture: null,
      deliveryAddress: "9 Isekhure Street, Benin City, Edo State",
      nearestLandmark: "Near St. Saviours Church",
      latitude: 6.3355,
      longitude: 5.601,
    },
    products: [{ bottleName: "Kayora Premium Water", size: "18.9L", quantity: 2, price: 2500, subtotal: 5000 }],
    amount: 5000,
    status: "Scheduled",
    paymentMethod: "Card",
    paymentStatus: "Paid",
    transactionId: "TXN-000902",
    deliveryType: "Scheduled",
    scheduledDate: new Date(now + 2 * 86400000).toISOString(),
    scheduledTime: "10:00 AM",
    priority: "Normal",
    delivery: { driverId: null, driverName: null, vehicle: null, estimatedDeliveryTime: null, distanceKm: null },
    timeline: [
      { label: "Order Created", timestamp: hoursAgo(0.5), completed: true },
      { label: "Payment Confirmed", timestamp: hoursAgo(0.5), completed: true },
      { label: "Waiting For Assignment", timestamp: null, completed: false },
      { label: "Driver Assigned", timestamp: null, completed: false },
      { label: "Out For Delivery", timestamp: null, completed: false },
      { label: "Delivered", timestamp: null, completed: false },
    ],
    specialInstructions: "Deliver only after 10AM, customer travelling before that.",
  },
  {
    id: "KYA-88271",
    orderDate: hoursAgo(0.2),
    customer: {
      name: "Emeka Nwosu",
      phone: "+234 808 901 2345",
      email: "emeka.nwosu2@gmail.com",
      profilePicture: null,
      deliveryAddress: "22 Uselu Lagos Road, Benin City, Edo State",
      nearestLandmark: "Uselu Junction",
      latitude: 6.3512,
      longitude: 5.6301,
    },
    products: [{ bottleName: "Kayora Premium Water", size: "75cl", quantity: 12, price: 500, subtotal: 6000 }],
    amount: 6000,
    status: "Preparing",
    paymentMethod: "Transfer",
    paymentStatus: "Paid",
    transactionId: "TXN-000905",
    deliveryType: "Instant",
    scheduledDate: null,
    scheduledTime: null,
    priority: "Urgent",
    delivery: { driverId: null, driverName: null, vehicle: null, estimatedDeliveryTime: null, distanceKm: null },
    timeline: [
      { label: "Order Created", timestamp: hoursAgo(0.2), completed: true },
      { label: "Payment Confirmed", timestamp: hoursAgo(0.2), completed: true },
      { label: "Waiting For Assignment", timestamp: hoursAgo(0.1), completed: true },
      { label: "Driver Assigned", timestamp: null, completed: false },
      { label: "Out For Delivery", timestamp: null, completed: false },
      { label: "Delivered", timestamp: null, completed: false },
    ],
    specialInstructions: "",
  },
];