import { Product } from "../types/product";

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "PRD-001",
    name: "Kayora Premium Water",
    description: "Purified premium table water, sealed for freshness.",
    size: "50cl",
    price: 300,
    imageUri: null,
    available: true,
    status: "Active",
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "PRD-002",
    name: "Kayora Premium Water",
    description: "Purified premium table water, sealed for freshness.",
    size: "75cl",
    price: 500,
    imageUri: null,
    available: true,
    status: "Active",
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: "PRD-003",
    name: "Kayora Premium Water",
    description: "Purified premium table water, ideal for everyday use.",
    size: "1L",
    price: 650,
    imageUri: null,
    available: true,
    status: "Active",
    createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    id: "PRD-004",
    name: "Kayora Premium Water",
    description: "Family-size bottle for home and office use.",
    size: "1.5L",
    price: 800,
    imageUri: null,
    available: true,
    status: "Active",
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: "PRD-005",
    name: "Kayora Premium Water",
    description: "Bulk 5L dispenser-friendly container.",
    size: "5L",
    price: 1500,
    imageUri: null,
    available: false,
    status: "Out of Stock",
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "PRD-006",
    name: "Kayora Premium Water",
    description: "Large refill container for offices and events.",
    size: "18.9L",
    price: 2500,
    imageUri: null,
    available: true,
    status: "Active",
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];