import { Vehicle } from "../types/vehicle";

/* ============================================================
   DEMO VEHICLE FLEET
   ------------------------------------------------------------
   Vehicle IDs here (v-1 through v-5) are already tied to the
   matching demo drivers in driversDemoData.ts (driver ids
   "1" through "5"), so the two demo datasets stay consistent —
   those five vehicles start out "Assigned" with assignedDriverId
   set. The rest are genuinely available for the wizard to pick.
============================================================ */

export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: "v-1",
    brand: "Toyota",
    model: "Hilux",
    vehicleType: "Pickup",
    plateNumber: "AKD-324-AA",
    engineNumber: "ENG-33920184",
    chassisNumber: "CHS-77281940",
    color: "White",
    image: null,
    registrationImage: null,
    status: "Assigned",
    assignedDriverId: "1",
  },
  {
    id: "v-2",
    brand: "Toyota",
    model: "Hiace",
    vehicleType: "Van",
    plateNumber: "AKD-245-KY",
    engineNumber: "ENG-88213409",
    chassisNumber: "CHS-99213409",
    color: "Kayora Blue",
    image: null,
    registrationImage: null,
    status: "Assigned",
    assignedDriverId: "2",
  },
  {
    id: "v-3",
    brand: "Ford",
    model: "Transit",
    vehicleType: "Van",
    plateNumber: "EDS-118-FB",
    engineNumber: "ENG-11029384",
    chassisNumber: "CHS-22938471",
    color: "Silver",
    image: null,
    registrationImage: null,
    status: "Assigned",
    assignedDriverId: "3",
  },
  {
    id: "v-4",
    brand: "Toyota",
    model: "Hilux",
    vehicleType: "Pickup",
    plateNumber: "EDS-902-GI",
    engineNumber: "ENG-55019283",
    chassisNumber: "CHS-66019283",
    color: "White",
    image: null,
    registrationImage: null,
    status: "Assigned",
    assignedDriverId: "4",
  },
  {
    id: "v-5",
    brand: "Suzuki",
    model: "APV",
    vehicleType: "Mini Truck",
    plateNumber: "EDS-441-EN",
    engineNumber: "ENG-77102938",
    chassisNumber: "CHS-88102938",
    color: "White",
    image: null,
    registrationImage: null,
    status: "Assigned",
    assignedDriverId: "5",
  },
  {
    id: "v-6",
    brand: "Toyota",
    model: "Hilux",
    vehicleType: "Pickup",
    plateNumber: "EDS-101-KY",
    engineNumber: "ENG-10192837",
    chassisNumber: "CHS-20293847",
    color: "Kayora Blue",
    image: null,
    registrationImage: null,
    status: "Available",
    assignedDriverId: null,
  },
  {
    id: "v-7",
    brand: "Foton",
    model: "Aumark",
    vehicleType: "Truck",
    plateNumber: "EDS-202-KY",
    engineNumber: "ENG-30394857",
    chassisNumber: "CHS-40495867",
    color: "White",
    image: null,
    registrationImage: null,
    status: "Available",
    assignedDriverId: null,
  },
  {
    id: "v-8",
    brand: "Bajaj",
    model: "RE",
    vehicleType: "Motorcycle",
    plateNumber: "EDS-303-KY",
    engineNumber: "ENG-50596877",
    chassisNumber: "CHS-60697877",
    color: "Kayora Blue",
    image: null,
    registrationImage: null,
    status: "Maintenance",
    assignedDriverId: null,
  },
  {
    id: "v-9",
    brand: "Toyota",
    model: "Hiace",
    vehicleType: "Van",
    plateNumber: "EDS-404-KY",
    engineNumber: "ENG-70798988",
    chassisNumber: "CHS-80899099",
    color: "White",
    image: null,
    registrationImage: null,
    status: "Available",
    assignedDriverId: null,
  },
];